import os
import yaml

_HERE = os.path.dirname(os.path.abspath(__file__))

_local = os.path.join(_HERE, "config_local.yaml")
_default = os.path.join(_HERE, "config.yaml")

_cfg_file = _local if os.path.exists(_local) else _default
CONFIG_FILE = _cfg_file

with open(_cfg_file) as _f:
    _cfg = yaml.safe_load(_f)

FOLDER_BEAM           = _cfg["FOLDER_BEAM"]
FOLDER_SCAN           = _cfg["FOLDER_SCAN"]
FOLDER_TOD_OUTPUT     = _cfg["FOLDER_TOD_OUTPUT"]
path_to_map           = _cfg["path_to_map"]
beam_file_I           = _cfg["beam_file_I"]
beam_file_Q           = _cfg["beam_file_Q"]
beam_file_U           = _cfg["beam_file_U"]
power_threshold_I     = _cfg["power_fraction_threshold_I"]
power_threshold_Q     = _cfg["power_fraction_threshold_Q"]
power_threshold_U     = _cfg["power_fraction_threshold_U"]
start_day             = _cfg["start_day"]
end_day               = _cfg["end_day"]
n_processes           = _cfg["n_processes"]
max_memory_per_process = _cfg["max_memory_per_process"]

# Optional calibration cache
calibration_skip        = _cfg.get("calibration_skip", False)
calibration_n_processes = _cfg.get("calibration_n_processes", None)
calibration_batch_size  = _cfg.get("calibration_batch_size", None)

# Optional beam pixel cache (generated by precompute_beam_cache.py)
beam_cache_dir  = _cfg.get("beam_cache_dir", None)
beam_cache_n_psi = _cfg.get("beam_cache_n_psi", 720)

# Beam grid interpolation method
# beam_interp_method: 'nearest'  → single nearest-pixel lookup (fastest)
#                     'bilinear' → 4-pixel bilinear HEALPix (default, fast Numba kernel)
#                     'gaussian' → isotropic Gaussian kernel (slower, no grid artefacts)
# Backward-compat: if only the old beam_interp_gaussian flag is set, map it.
_interp_method_raw = _cfg.get("beam_interp_method", None)
if _interp_method_raw is None:
    _old_gaussian      = _cfg.get("beam_interp_gaussian", False)
    _interp_method_raw = 'gaussian' if _old_gaussian else 'bilinear'
_VALID_INTERP = {'nearest', 'bilinear', 'gaussian'}
if _interp_method_raw not in _VALID_INTERP:
    raise ValueError(
        f"beam_interp_method must be one of {sorted(_VALID_INTERP)!r}, "
        f"got {_interp_method_raw!r}"
    )
beam_interp_method     = _interp_method_raw
beam_interp_sigma_deg  = _cfg.get("beam_interp_sigma_deg",  None)   # None → pixel resolution
beam_interp_radius_deg = _cfg.get("beam_interp_radius_deg", None)   # None → 3 × sigma
